### ISSUE TITLE
Article en PDF

### ISSUE THREAD

**Issue by wdhif** [smaltcreation/inck#107]
Lorsque l'on clique sur le bouton pdf, le serveur renvoi une erreur 500

**Comment by wdhif** [comment]
Le bug est encore présent sur le serveur, on obtient une erreur 500 lorsque l'on clique sur les boutons PDF, que l'article ai ou pas des vidéos.

**Comment by samybob1** [comment]
C'était un problème de permissions en prod ;)

**Comment by wdhif** [comment]
Encore un petit problème, pour l'article sur UnrealEngine, le pdf est vide. https://www.inck.fr/article/8/unrealengine-historique-d-un-des-meilleur-moteur-moderne

C'est peut-être à cause du "well" comme c'est le seul article avec ça.
