### ISSUE TITLE
Erreur 500 lors de la connexion via Google+

### ISSUE THREAD

**Issue by WaSa42** [SmaltCreation/Inck#124]
Une erreur 500 survient après la connexion via Google+
* Trouver le bug et le corriger
* Si le bug est coriace, supprimer temporairement le bouton pour se connecter via Google+

**Comment by WaSa42** [comment]
Il me semble que l'erreur vient du fait que l'adresse email existe déjà en base.
Bien sûr, il m'est impossible de tester en dev car google n'accepte pas des redirect_uri venant d'un domaine autre que de premier niveau.
@Dridzou : le bundle n'est-il pas censé fusionner les comptes ?

**Comment by Dridzou** [comment]
Ca remonte, mais de mémoire le bundle doit log l'user si celui-ci essaie de register avec une adresse qui existe déjà.

**Comment by WaSa42** [comment]
Ok, il me semblait aussi. Je vais devoir me pencher plus en détail sur le problème.
Merci pour ta réponse.

**Comment by WaSa42** [comment]
Il est en fait illogique qu'un utilisateur se connecte avec Facebook puis veut se connecter avec la même adresse email que celle de Facebook.
