### ISSUE TITLE
Cron générant le sitemap.xml

### ISSUE THREAD

**Issue by WaSa42** [SmaltCreation/Inck#135]
* Vérifier que le cron tourne bien et que le sitemap.xml est bien regénéré à chaque passage du cron
* Le bundle utilisé pour générer le sitemap est celui-ci : https://github.com/prestaconcept/PrestaSitemapBundle
* Le cron en question exécute normalement ```php app/console prestap:sitemaps:dump```

**Comment by wdhif** [comment]
Le cron ne fonctionne pas, @WaSa42 je ne sais pas comment t'a régler le bundle mais il n'y a pas de tache cron pour root ni pour www-data

**Comment by wdhif** [comment]
J'ai changer l'attribution de la tache, c'est l'user root qui s'en chargera (plus nrouvière) et j'ai modifier la tache avec des chemins absolus.
Egalement correction de la tache, elle dirigeait vers un fichier et non un script.
