### ISSUE TITLE
Sécuriser Inck avec HTTPS

### ISSUE THREAD

**Issue by WaSa42** [SmaltCreation/Inck#137]
Trouver le moyen de passer Inck en HTTPS.

**Comment by wdhif** [comment]
La sécurisation de Inck est terminer, le certificat ssl est générer et installer, il ne manque plus que les websockets en ssl, voir #144

**Comment by WaSa42** [comment]
Afficher l'identité de la société comme le font tous les autres sites, exemple : GitHub.
![ssl](https://cloud.githubusercontent.com/assets/6498751/6919370/b2300ae4-d7b6-11e4-8707-6e4e6ca32e15.png)
![ssl2](https://cloud.githubusercontent.com/assets/6498751/6919391/d5c7b84e-d7b6-11e4-9d01-0cc749716a2b.png)

**Comment by wdhif** [comment]
Notre certificat SSL ne permet pas la validation de l'organisation, seulement celle du domaine.
Les certificat permettant la validation de l'organisation coûte 35€ par an minimum.
