### ISSUE TITLE
Problème affichage bouton jumbotron

### ISSUE THREAD

**Issue by Jitrixis** [SmaltCreation/Inck#142]
Les liens dans les jumbotron appraissent blanc par défaut et sont donc invisible. (Setting/Edit user profil)

![capture du 2015-03-26 03 21 58](https://cloud.githubusercontent.com/assets/3462094/6839352/6a724904-d367-11e4-8a0f-b89b429c1a09.png)

**Comment by samybob1** [comment]
Effectivement, chez moi aussi !
