### ISSUE TITLE
Websocket non fonctionnels

### ISSUE THREAD

**Issue by wdhif** [SmaltCreation/Inck#144]
Je créer une issue pour nous permettre de garder une trace de ce que l'ont fait pour régler ce bug : 

En production, sur le port 8080 on obtient ceci : 
ws://inck.fr:8080/main' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

Donc une 403

Tout fonctionne en dev et prod local.
Si on utilise un reverse proxy (Nginx) on obtient une 404.
Les websockets ont déjà fonctionnés par le passé sur le port 443 (https) mais aujourd'hui ce n'est plus le cas, on obtient la même erreur qu'en 8080 soit une 403.
Les ports avec ovh sont ouvert de base, testé avec le simplehttp en python.

**Comment by samybob1** [comment]
Le _cross domain_ est interdit, `inck.fr` est redirigé vers `www.inck.fr` donc pour les _websockets_ il faut se connecter sur `ws://www.inck.fr:85`.

**Comment by wdhif** [comment]
Je réouvre l'issue pour écrire les nouvelles infos.
Les port étant bloqué à Supinfo, les ws sur 85 fonctionne, mais après le passage du site en ssl, il sont à nouveaux bloqué.
Soit car la connexion est refusé car on utilise le ws et non le wss.
Soit, si on utilise wss, la connexion n'abouti pas.
Le mieux est donc d'utilise un reverse proxy avec Nginx

**Comment by wdhif** [comment]
Les websockets sont fonctionnels en utilisant un certificat ssl pour le sous-domaine (ws.inck.fr)
