### ISSUE TITLE
404 Si on change le titre d'un article

### ISSUE THREAD

**Issue by wdhif** [SmaltCreation/Inck#145]
Si on change le titre d'un article et qu'on fait enregistrer en tant que brouillon (et probablement aussi si on le publie) on prends un 404 car le lien ne change pas en direct, mais seulement après actualisation. Un ID pour les articles pourrait peut-être résoudre ce soucis.

**Comment by WaSa42** [comment]
L'erreur venait du faite que l'utilisateur fît précédent après avoir changé le nom de l'article. Du coup, le slug différait de celui qui avait été fraîchement changé avec le titre. La route n'était donc plus bonne et une 404 était renvoyée.
