### ISSUE TITLE
Traductions dans les mails

### ISSUE THREAD

**Issue by WaSa42** [smaltcreation/inck#146]
Parfois la traduction ne passe pas dans les mails d'activation/confirmation.

![Issue trads](https://cloud.githubusercontent.com/assets/7241592/8823632/c20deb82-306e-11e5-805f-819aec334241.jpg)

**Comment by arnaud-roche** [comment]
![trad-mail](https://cloud.githubusercontent.com/assets/7241592/8823632/c20deb82-306e-11e5-805f-819aec334241.jpg)

**Comment by arnaud-roche** [comment]
Le bug ne se produit qu'en prod et pas sur l'environnement de dev
