### ISSUE TITLE
Changer le logo de Inck

### ISSUE THREAD

**Issue by WaSa42** [smaltcreation/inck#152]
Changer le logo de Inck par : 
![Nouveau logo](http://img15.hostingpics.net/pics/679394incklogo.png)

Faire cela pour : 
- [x] Le favicon
- [ ] Google
- [x] Facebook

**Comment by wdhif** [comment]
Le logo sur google developers console devra être changé au moment de la mise en prod par : https://www.inck.fr/inck-logo.png
