### ISSUE TITLE
StatBundle et fonctions clefs

### ISSUE THREAD

**Issue by WaSa42** [SmaltCreation/Inck#79]
* Pour des entités majeures du Projet, lister les fonction clefs pour récupérer les statistics : 
  * User
  * Article
  * Category
  * Tag
* Bien penser à différencier les fonctions de l'entité Statistics et les Query Builders de l'entité sujet aux stats.
* Faire valider ces fonctions
* Les réaliser

**Comment by wdhif** [comment]
Tache a redéterminer.

**Comment by WaSa42** [comment]
Issue à redéterminer dans le futur.
#statsRefactoring
