### ISSUE TITLE
Badges et glorifications

### ISSUE THREAD

**Issue by WaSa42** [smaltcreation/inck#85]
- Mettre en place un système de badge sur l'utilisateur
- Il serait excellent d'avoir un créateur de badge qui demande : 
  - Un nom
  - Une abréviation
  - Une icône (parmis la liste de font-awesome)
  - Une couleur pour le fond et le texte (colerpicker)

**Comment by wdhif** [comment]
Il faudrait penser à ce qu'on mettrait pour ces badges et autres succès, je pense que ce serait vraiment un super ajout pour Inck, on devrait l'avancer à la 1.4.0 non ?

**Comment by WaSa42** [comment]
- [ ] Ajouter le bouton de création dans panel de d'admin
- [ ] Réadapter le formulaire de création
- [ ] Corriger le le formulaire d'édition (colorpicker)
- [ ] Supprimer le champs date du formulaire
- [ ] Ajouter le champs d'importance (style z-index)
- [ ] Faire une page qui permet d'ajouter de façon simple des utilisateurs à un badge
  - Pour cela, sur la page (/show) d'un badge, afficher les utilisateur qui possèdent le badge et un bouton pour en ajouter d'autres
  - Il doit être facile d'ajouter des nouveaux utilisateurs (select2 avec autocomplétion et champs multiples)
  - Penser à la pagination
- [ ] Les 3 badges les plus importants doivent s'afficher sur le profil de l'utilisateur
- [ ] L'utilisateur doit être notifié lorsqu'il se voit attribuer un badge
- [ ] Les utilisateurs abonnés à l'auteur seront aussi notifiés
- [ ] Une activité peut être créée pour être enregistré dans son historique personnel

**NB: pour les notifications, si besoin d'aide, contacter @samybob1 et pour les activités, contacter @WaSa42**
